---
- hosts: all
  gather_facts: true

  tasks:
    # Check host with rkhunter
    - name: Check host with rkhunter
      become: true
      become_user: root
      ansible.builtin.command:
        cmd: /usr/bin/rkhunter --cronjob --quiet
      ignore_errors: true

    # Store the rkhunter output locally
    - name: Store the rkhunter output locally
      ansible.builtin.fetch:
        src: /var/log/rkhunter/rkhunter.log
        dest: results/rkhunter/
