---
- name: Audit local host with rkhunter
  hosts: all
  gather_facts: true

  tasks:
    - name: Rkhunter audit run
      become: true
      become_user: root
      ansible.builtin.command:
        cmd: /usr/bin/rkhunter --cronjob --quiet
      register: rkhunter_check_playbook
      changed_when: false
      failed_when: "'FAILED' in rkhunter_check_playbook.stderr"

    - name: Store the rkhunter output locally
      ansible.builtin.fetch:
        src: /var/log/rkhunter/rkhunter.log
        dest: results/rkhunter/
        mode: 0644
