---
- hosts: all
  gather_facts: true

  tasks:
    # Check host with lynis
    - name: Check host with lynis
      become: true
      become_user: root
      ansible.builtin.command:
        cmd: /usr/bin/lynis audit system --quick --auditor "Ansible" --quiet
      ignore_errors: true

    # Store the lynis output locally
    - name: Store the lynis log locally
      ansible.builtin.fetch:
        src: /var/log/lynis.log
        dest: results/lynis/

    - name: Store the lynis report locally
      ansible.builtin.fetch:
        src: /var/log/lynis-report.dat
        dest: results/lynis/
