---
- name: Audit local host with rkhunter
  hosts: all
  gather_facts: true

  tasks:
    - name: rkhunter audit run
      become: true
      become_user: root
      ansible.builtin.command:
        cmd: /usr/bin/rkhunter --cronjob --quiet
      ignore_errors: true

    - name: Store the rkhunter output locally
      ansible.builtin.fetch:
        src: /var/log/rkhunter/rkhunter.log
        dest: results/rkhunter/
